### PR TITLE
TelegramError, added parameters

### PR DESCRIPTION
**Pull request by JosephBlock**
This will add telegrams parameters response in TelegramError.

Example: 
`TelegramError('[Error]: Bad Request: group chat is migrated to supergroup chat', 400)`
changes to:
`TelegramError('[Error]: Bad Request: group chat is migrated to supergroup chat', 400, {'migrate_to_chat_id': xxxxxxxxxx})`

### CODE REVIEW

**Comment by nickoala** [comment]
Sorry, I miss your pull request in the latest update. I will include it within the next 3 days.

**Comment by nickoala** [comment]
Is it possible to show me the raw JSON response returned by Telegram servers? Thank you.

**Comment by JosephBlock** [comment]
@nickoala Added raw_response

**Comment by nickoala** [comment]
No. that's NOT what I mean. I am saying, can *you* show me the raw JSON response? I can't easily reproduce this error, but I want to see the exact JSON response before deciding how the code should be modified. I need your help.

Can *you* post the raw JSON response here? Thank you very much. :smile:

**Comment by JosephBlock** [comment]
Whoops, I'll get that soon.

**Comment by JosephBlock** [comment]
@nickoala json response
 `{
  "ok": false,
  "error_code": 400,
  "description": "[Error]: Bad Request: group chat is migrated to supergroup chat",
  "parameters": {
    "migrate_to_chat_id": -xxxxxxxxxxxx
  }
}`

**Comment by nickoala** [comment]
Thanks Joseph. Someone is suggesting similar things (embedding more info in exceptions) in another discussion. I want to give it some thoughts before deciding what to do. I will keep you update.

**Comment by JosephBlock** [comment]
My current use is a sync bot which stores the chat ID. But when a chat coverts to a supergroup it would break.  The extra info helps the bot to update the chat ID to the new one automatically.

**Comment by nickoala** [comment]
Hi @JosephBlock, I have updated telepot, now at version 6.8

I chose a different method to integrate extra parameters into `TelegramError`. Now, `TelegramError` has a property `json` which is the underlying JSON object giving rise to the exception. Assuming you call the exception `ex`, this is how you access `migrate_to_chat_id`:

```python
ex.json['parameters']['migrate_to_chat_id']
```

Thanks for pointing this out. You help make telepot better.

**Pull request closed without merging**
