### PR TITLE
Handle http_proxy environment variable

### PR DESCRIPTION
**Pull request by insanediv**
I had several issues making the library work behind enterprise proxies using the async http mode. This fix works well

### CODE REVIEW

**Comment by insanediv** [comment]
@das7pad I applied the update. More info in the commit description

**Comment by das7pad** [comment]
_I might have to revert my approve._ I could not find a recent version of Linux SUSE that is **not** capable of uppercase environment variables. @insanediv Which SUSE version are you using?

We could drop the duplicate lookup to improve performance and require using the uppercase version `HTTP_PROXY`.

**Comment by insanediv** [comment]
Hi @das7pad I'm running your library on enterprise branch of SUSE (**SUSE sles12.2**). I'm configuring proxy the persistent way by editing 
`/etc/sysconfig/proxy`

**Comment by das7pad** [comment]
Thanks for the hint.
We could use the mentioned stdlib function from that thread: `urllib.request.getproxies`
```python
HTTP_PROXY = urllib.request.getproxies().get('http')
```

**Comment by nickoala** [comment]
@insanediv and @das7pad, thanks for the work.

After some considerations, I have decided the existing methods of using proxy is too ad-hoc. If we want to give both traditional and async version proxy support, at least I should make it consistent. I have done that in the newest version 12.4. Please refer to #309 for usage.

**Pull request merged**
