### PR TITLE
Method to re-format HTML text, received as plain text and its entities.

### PR DESCRIPTION
**Pull request by SiteEffect**
This PR focuses to solve Issue #260 and as a result let's you recover text messages from updates to HTML marked up strings.

### CODE REVIEW

**Comment by nickoala** [comment]
Hi @Arengo, this is awesome. I accept your suggestions in principle. But if it's going to handle bold and italic in HTML, for completeness it should also handle other [decorations in HTML and Markdown](https://core.telegram.org/bots/api#formatting-options). I will accept your submission after some time, after I decide how to integrate the whole thing (including HTML and Markdown) into telepot. Thank you!

**Comment by Arengo** [comment]
Thanks for the feedback. If you request changes I am keen to address them, as soon as you want to tackle this. I am running this modification on my telepot application right now and it works flawlessly. I agree that additional decorations should be handled as well, but I am unsure if all - like mentions (@) or hashtags (#) - are working the same with text messages like the current HTML are doing. However, HTML and Markdown themselves should be no problem to address in this method.

**Comment by SiteEffect** [comment]
Added support for Markdown and included the common HTML and Markdown entities.

**Comment by nickoala** [comment]
@SiteEffect (did you change your name), thanks for the effort, but the complications are more than that. What if the text contains special characters (e.g. `>`, `<`, `&` in HTML, `_`, `*` in Markdown)? After applying the entities to the string, the user should reasonably expect that all special characters are also properly escaped. 

Escaping them *before* applying entities may screw up the offsets. Escaping them *after* applying entities is hard because you got a lot more special characters mixed in. If you want a function to apply entities in a reasonable way, that function should also take care of escaping special characters properly.

Given all that extra work, I would prefer the entity-applying function to be in a separate module. I am thinking of implementing that myself. It's up to you if you want to go ahead yourself. :smile: Thanks anyway.

**Comment by nickoala** [comment]
This is my preliminary version for markdown, along with a test at the end. Note that I split the string into a list of chars before escaping, so as not to affect the offsets in entities. Another subtlety is that special characters contained within an entity should not be escaped (this may be different in HTML).

```python
def format_markdown(string, entities):
    # incomplete 
    char_map = {'*': '\\*',
                '_': '\\_',}

    formatter = {'bold':      lambda s,e: '*'+s+'*',
                 'italic':    lambda s,e: '_'+s+'_',
                 'text_link': lambda s,e: '['+s+']('+e['url']+')',
                 'code':      lambda s,e: '`'+s+'`',
                 'pre':       lambda s,e: '```text'+s+'```'}

    def inside_some_entities(i):
        return any(map(lambda e: e['offset'] <= i < e['offset']+e['length'], entities))

    # Escape special characters
    seq = map(lambda c,i:
                  char_map[c]
                      if c in char_map and
                          not inside_some_entities(i) else c,
              list(string),          # split string to char sequence
              range(0,len(string)))  # along with each char's index

    offset = 0
    result = ''

    for e in entities:
        f,n,t = e['offset'], e['length'], e['type']

        result += ''.join(seq[offset:f])

        if t in formatter:
            result += formatter[t](''.join(seq[f:f+n]), e)
        else:
            result += ''.join(seq[f:f+n])

        offset = f + n

    result += ''.join(seq[offset:])
    return result


entities = [
    {'type': 'bold', 'offset': 0, 'length': 3},
    {'type': 'italic', 'offset': 3, 'length': 3},
    {'type': 'text_link', 'offset': 9, 'length': 6, 'url': 'www.yahoo.com'},
]

print format_markdown('a_bcdefh*ijklm*nopq', entities)
```

**Comment by nickoala** [comment]
I have added this functionality to package `telepot.text` in the latest release of telepot. Thanks for suggesting.

**Pull request closed without merging**
